// Status words shown while Jarvis is computing a reply. Mix of single gerunds
// and short in-character phrases. Picked at random and rotated in ChatDock.
export const THINKING_WORDS = [
  "Computing",
  "Pondering",
  "Rambling",
  "Calibrating",
  "Synthesizing",
  "Cogitating",
  "Deliberating",
  "Reasoning",
  "Analyzing",
  "Processing",
  "Theorizing",
  "Speculating",
  "Hypothesizing",
  "Contemplating",
  "Ruminating",
  "Crunching",
  "Parsing",
  "Inferring",
  "Deducing",
  "Extrapolating",
  "Formulating",
  "Strategizing",
  "Optimizing",
  "Iterating",
  "Reticulating",
  "Triangulating",
  "Correlating",
  "Aggregating",
  "Distilling",
  "Untangling",
  "Decoding",
  "Assembling",
  "Compiling",
  "Tinkering",
  "Pondering deeply",
  "Mulling it over",
  "Connecting the dots",
  "Consulting the archives",
  "Spinning up neurons",
  "Warming up the circuits",
  "Cross-referencing memory",
  "Querying the knowledge base",
  "Running the numbers",
  "Sifting through context",
  "Weighing the options",
  "Aligning the vectors",
  "Tuning the heuristics",
  "Polishing the answer",
  "Consulting my better judgment",
  "Recalibrating priorities",
  "Booting up cleverness",
  "Engaging higher reasoning",
  "Summoning insight",
  "Threading the logic",
  "Folding the proteins",
  "Charging the flux capacitor",
  "Greasing the gears",
  "Loading wisdom",
  "Channeling brilliance",
  "Cracking the problem",
  "Tracing the threads",
  "Mapping the territory",
  "Drawing conclusions",
  "Sharpening the analysis",
  "Refining the response",
  "Brewing thoughts",
  "Percolating ideas",
  "Marinating on it",
  "Chewing it over",
  "Gathering my thoughts",
  "Searching the depths",
  "Scanning the horizon",
  "Plotting the path",
  "Sketching the outline",
  "Stitching it together",
  "Wiring the synapses",
  "Aligning the stars",
  "Doing the math",
  "Considering the angles",
  "Examining the evidence",
  "Building the case",
  "Joining the puzzle pieces",
  "Distilling the essence",
  "Filtering the noise",
  "Amplifying the signal",
  "Tracking down the answer",
  "Hunting for clarity",
  "Wrangling the data",
  "Herding the bits",
  "Spinning the wheels",
  "Turning the cogs",
  "Flipping the switches",
  "Priming the engine",
  "Revving the processors",
  "Fetching insight",
  "Indexing the memories",
  "Sorting the possibilities",
  "Balancing the equation",
  "Squaring the circle",
  "Bending the logic",
  "Connecting neurons",
  "Lighting up the cortex",
  "Consulting the oracle",
  "Reading the tea leaves",
  "Decoding the signal",
  "Unpacking the request",
  "Framing the answer",
  "Drafting a reply",
  "Composing thoughts",
  "Arranging the words",
  "Choosing the words",
  "Picking the right words",
  "Measuring twice",
  "Double-checking the logic",
  "Verifying the facts",
  "Auditing my reasoning",
  "Sanity-checking",
  "Reconsidering",
  "Second-guessing wisely",
  "Probing the edges",
  "Testing the theory",
  "Modeling the outcome",
  "Simulating scenarios",
  "Forecasting the answer",
  "Calculating trajectories",
  "Resolving the ambiguity",
  "Clarifying the intent",
  "Reading between the lines",
  "Grasping the nuance",
  "Catching the drift",
  "Tuning into the question",
  "Focusing the lens",
  "Adjusting the dials",
  "Fine-tuning the response",
  "Almost there",
  "Putting it together",
  "Wrapping my head around it",
  "Doing my homework",
  "Thinking it through",
];
